[package]
name = "solana-reconcile"
description = "Blockchain, Rebuilt for Scale"
authors = ["Solana Maintainers <maintainers@solana.com>"]
edition = "2018"
version = "0.1.1"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"

[dependencies]
csv = "1.1.3"
clap = "2.33.0"
console = "0.10.3"
indexmap = "1.3.2"
serde = { version = "1.0", features = ["derive"] }
solana-clap-utils = {git = "https://github.com/solana-labs/solana", rev = "efb4988d108fa2f52c35d671a177d3b18db6c495"}
solana-cli-config = {git = "https://github.com/solana-labs/solana", rev = "efb4988d108fa2f52c35d671a177d3b18db6c495"}
solana-client = {git = "https://github.com/solana-labs/solana", rev = "efb4988d108fa2f52c35d671a177d3b18db6c495"}
solana-remote-wallet = {git = "https://github.com/solana-labs/solana", rev = "efb4988d108fa2f52c35d671a177d3b18db6c495"}
solana-runtime = {git = "https://github.com/solana-labs/solana", rev = "efb4988d108fa2f52c35d671a177d3b18db6c495"}
solana-sdk = {git = "https://github.com/solana-labs/solana", rev = "efb4988d108fa2f52c35d671a177d3b18db6c495"}
solana-stake-program = {git = "https://github.com/solana-labs/solana", rev = "efb4988d108fa2f52c35d671a177d3b18db6c495"}
tempfile = "3.1.0"

[dev-dependencies]
solana-core = {git = "https://github.com/solana-labs/solana", rev = "efb4988d108fa2f52c35d671a177d3b18db6c495"}
